# Generated by Django 4.1.7 on 2023-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_manager_user_manager_id_user_ptin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager_id',
            field=models.IntegerField(null=True, verbose_name='Manager Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ptin',
            field=models.CharField(max_length=10, null=True, verbose_name='PTIN'),
        ),
    ]
