# Generated by Django 4.1.7 on 2023-02-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='certificate',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
