# Generated by Django 4.1.7 on 2023-02-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_log', '0002_alter_credit_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='certificate',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
