# Generated by Django 4.1.7 on 2023-02-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_log', '0003_alter_credit_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='certificate',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
