# Generated by Django 4.1.7 on 2023-02-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_log', '0006_alter_credit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='agent_first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='agent_last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
